blank_issues_enabled: false
contact_links:
  - name: ✏️ FAQ
    url: https://github.com/amd64fox/SpotX/blob/main/.github/Doc/FAQ.md#faq
    about: Read the frequently asked questions, maybe it will help solve your problem right now.